### ISSUE TITLE
是我没看懂需求么?

### ISSUE THREAD

**Issue by sxd1140** [tmac1999/FindInProjectView#1]
看图的功能 不是点
![image](https://cloud.githubusercontent.com/assets/541212/20552585/7330e6ea-b187-11e6-8c0c-e8ae2fe111b7.png)这里么?
还是我没弄懂需求

**Comment by tmac1999** [comment]
是的。。。你说的对。。。
弄完这个插件 我就发现有另外的方法可以直接复制文档了。 直接右键点击导航栏也可以复制。。
囧
后来在博客里写了，这里没人看一直没改。。
原来这个叫Scroll from source。。
害的我各种 关键词搜索半天搜不到。蛋疼。
谢啦~~

**Comment by sxd1140** [comment]
不过也蛮好的 可以走一遍插件制作流程
